### ISSUE TITLE
Dependencies are unavailable

### ISSUE THREAD

**Issue by ccvca** [mpostol/ASMD#52]
Hello,
The CAS-Dependencies are not included in this github repository. Is this intended?
https://github.com/mpostol/ASMD/blob/5659c2b7cc2d4b54a454f5842988f32156217297/ModelDesigner.DesignStudio/ModelDesigner.DesignStudio.csproj#L94-L141

Some of them can be found on your github Account, but not all of them.

EDIT: While importing there is also anoter error, that "ModelingProject" ist not supported, is a special Visual Studio version required?

Greetings

**Comment by ccvca** [comment]
After some reloads, Visual Studio (and I) found the CAS-Dependencies.
After unloading the Test-Project there are only some Errors missing:
That the following Namespaces are not available:
```
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
```

**Comment by ccvca** [comment]
Found a solution myself:
DocumentFormat.OpenXml, Version=2.5.5631.0
This version is no longer available, but installing 2.7. compiles fine.

**Comment by mpostol** [comment]
Thanks, I will review the documentation.  It is related to #36 and #50 so fix it as a slave.

**Comment by mpostol** [comment]
Duplicates #4.
